---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml
    - vars/token.yml
    - vars/switch-tenant.yml

  tasks:
    - name: Get token task
      import_tasks: tasks/token.yml

    - name: get account tenant ids
      import_tasks: tasks/get-master-account-id.yml

    - name: switch account
      import_tasks: tasks/switch-tenant.yml

    - name: get account tenant ids
      import_tasks: tasks/list-tenants-per-mssp.yml
