---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml
    - vars/token.yml

  tasks:
    - name: Get token task
      import_tasks: tasks/token.yml

    - name: get account tenant ids
      import_tasks: tasks/list-tenants.yml
