---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml
    - vars/token.yml
    - vars/switch-tenant.yml
    - vars/assign-user-center-account.yml
    - vars/user-center-login.yml

  tasks:
    - name: Get token task
      import_tasks: tasks/token.yml

    - name: get account tenant ids
      import_tasks: tasks/get-tenants.yml

    - name: switch account
      import_tasks: tasks/switch-tenant.yml

    - name: get list of user center accounts
      import_tasks: tasks/get-user-center-accounts.yml

    - name: assign contract to customer account
      import_tasks: tasks/assign-user-center-account.yml
