---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks:
    - name: List ws1 users
      import_tasks: tasks/list-ws1-users.yml

    - name: activate ws1 user
      import_tasks: tasks/deactivate-ws1-user.yml