---

- name: Make HTTP POST request with cookie to assign license to tenant
  uri:
    url: "https://cloudinfra-gw.portal.checkpoint.com/api/v1/tenant/license/account/activate"
    method: POST
    headers:
      cookie: "{{ cookie_string }}"
    body_format: json
    body: "{{ assign_user_center_account | to_json }}"
    return_content: true
  register: assign_user_center_account_response
  failed_when: assign_user_center_account_response.status != 200 and assign_user_center_account_response.status != 201
