---

- name: Make HTTP POST request with cookie to create UEM-WS1 integration
  uri:
    url: "https://cloudinfra-gw.portal.checkpoint.com/app/SBM/api/airwatch_settings/?tenantId={{ tenantID }}"
    method: POST
    headers:
      cookie: "{{ cookie_string }}"
    body_format: json
    body: "{{ create_uem | to_json }}"
    return_content: true
  register: ti
  failed_when: ti.status != 200 and ti.status != 201
