---

- name: Make HTTP GET request with cookie to get list of tenants this user has access
  uri:
    url: "https://cloudinfra-gw.portal.checkpoint.com/api/v1/user/tenants"
    method: GET
    headers:
      cookie: "{{ cookie_string }}"
    return_content: true
  register: tenants_response
  failed_when: tenants_response.status != 200 and tenants_response.status != 201

- name: Print response
  debug:
    var: tenants_response

- name: Creating a new variable to store tenant id
  set_fact:
    account_id: "{{ tenants_response | json_query('json.tenants[?name== `' + master_account_name + '`].id') | first }}"

- name: Print accountId
  debug:
    var: account_id

- name: Print account name
  debug:
    var: account_name
